name: Publish npm
description: Publishes JavaScript npm package to GitHub Packages

inputs:
  tag:
    description: tag to register the published package with
    required: false
    default: "latest"
  working-directory:
    description: Path of the package.json
    required: false
    default: "."

runs:
  using: composite

  steps:
    - name: Create ~/.npmrc file
      shell: bash
      run: |
        echo "@${{ github.repository_owner }}:registry=https://npm.pkg.github.com/" > $HOME/.npmrc
        echo "//npm.pkg.github.com/:_authToken=${{ github.token }}" >> $HOME/.npmrc
        chmod 0600 $HOME/.npmrc

    - name: Publish npm
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        npm publish --tag ${{ inputs.tag }}
